export enum TeamRole {
    CEO = 'ceo',
    CTO = 'cto',
    CFO = 'cfo',
    ENGINEERING_MANAGER = 'engineering_manager',
    TECH_LEAD = 'tech_lead',
    DEVOPS_LEAD = 'devops_lead',
    SENIOR_DEVELOPER = 'senior_developer',
    DEVELOPER = 'developer',
    JUNIOR_DEVELOPER = 'junior_developer',
    QA_LEAD = 'qa_lead',
    QA_ENGINEER = 'qa_engineer',
    PRODUCT_MANAGER = 'product_manager',
    DESIGNER = 'designer',
    BUSINESS_ANALYST = 'business_analyst',
    VIEWER = 'viewer',
}

export enum PermissionResource {
    TEAM = 'team',
    PROJECT = 'project',
    DEPLOYMENT = 'deployment',
    ENVIRONMENT = 'environment',
    REPOSITORY = 'repository',
    SETTINGS = 'settings',
    MEMBERS = 'members',
    BILLING = 'billing',
    ANALYTICS = 'analytics',
    LOGS = 'logs',
    SECRETS = 'secrets',
    DOMAINS = 'domains',
    INTEGRATIONS = 'integrations',
}

export enum PermissionAction {
    CREATE = 'create',
    READ = 'read',
    UPDATE = 'update',
    DELETE = 'delete',
    DEPLOY = 'deploy',
    ROLLBACK = 'rollback',
    INVITE = 'invite',
    REMOVE = 'remove',
    PROMOTE = 'promote',
    DEMOTE = 'demote',
    CONFIGURE = 'configure',
    VIEW_LOGS = 'view_logs',
    MANAGE_SECRETS = 'manage_secrets',
    MANAGE_BILLING = 'manage_billing',
}
